### ISSUE TITLE
Issue with next version of ggraph

### ISSUE THREAD

**Issue by thomasp85** [cran/LabApplStat#1]
I'm preparing a new version of ggraph and LabApplStat is showing issues with some of the changes.

Specifically ggraph is moving to a vctrs backed implementation of the edge cap geometries and the extraction of the `label_rect` dimensions you do in the `plot.designDiagram` is no longer supported. If really needed you can get the size using the `field()` function from vctrs like so:

```
grid::unit(vctrs::field(x, 'width'), vctrs::field(x, 'width_unit'))
```

Be aware that this doesn't work for older versions of ggraph so it might be best to prepare a fix and wait for ggraph to be released before submitting.

I plan to submit ggraph next week

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by thomasp85** [comment]
😅 sorry
